### PR TITLE
Refactoring. Tests added.

### PR DESCRIPTION
**Pull request by joeldbirch**
Further refactoring to extract parts of the `filter_images` god-function into smaller, named functions with tests to match. Intending to continue this work and further reduce the size of `filter_images` in a later pull request. I'd like to have the safety net of a thorough test suite before tackling the various reported issues.

I'm using PHPUnit's "ReflectionMethod" class in order to test private methods.

I still have more work to do to get the encapsulation perfect, but I'd like to submit this pull request as a sort-of halfway point milestone, and to see if you have any feedback so far.

### CODE REVIEW

**Comment by joeldbirch** [comment]
What do you think? Too many changes?

**Comment by jhabdas** [comment]
Fork it

**Comment by joeldbirch** [comment]
Makes sense. Thanks. (Replying to deleted comment).

**Comment by ghost** [comment]
@joeldbirch depending on your use case you could also skip the plugin altogether and do something like this in your `functions.php`:

```php
/**
 * Filters content. Useful for adjusting output markup.
 *
 * @since WordCamp Ubud 2017
 * @param string $content Data to be filtered.
 * @link https://github.com/aFarkas/lazysizes
 * @link http://stackoverflow.com/a/20499803/712334
 * @link http://devdocs.io/php/class.domelement
 */
function wc_filter_content($content) {
  // Bail if not in loop or main query
  if ( !(is_single() && in_the_loop() && is_main_query()) ) {
    return $content;
  }

  // Create a DOM document and load the content into it
  $content = mb_convert_encoding($content, 'HTML-ENTITIES', "UTF-8");
  $document = new DOMDocument();
  libxml_use_internal_errors(true);
  $document->loadHTML(utf8_decode($content));

  // Query the document and modify it
  $images = $document->getElementsByTagName('img');
  foreach ($images as $image) {
    $image->removeAttribute('src');
    $image->setAttribute('class','lazyload');
  }

  // Save and return
  $html = $document->saveHTML();
  return $html;
}
add_filter('the_content', 'wc_filter_content');
```

**Note:** This will be moved to a gist or Pen in the next day.

**Comment by ghost** [comment]
> What do you think? Too many changes?

Regarding that, I'd just say too many commits. Probably scared people off. Might be useful to squash them next time before opening the pull with `git rebase -i HEAD~20`.

**Comment by jhabdas** [comment]
You may also _really_ enjoy: https://github.com/adrinux/web-starter-hugo

**Comment by jhabdas** [comment]
Whoops. Wrong tab xD

**Pull request closed without merging**
