### PR TITLE
Pullrequest with tests. Setting LazySizes config via wp_localize_script rather than direct script printing.

### PR DESCRIPTION
**Pull request by joeldbirch**
Hello,

I've been meaning to help out on this great plugin, and finally had time. I have fixed the part indicated by your comment `@FIXME Script printing is bad habit` by using the preferred method of `wp_localize_script`.

One thing I'm not sure you'll like is that I am using the server-side `wp_is_mobile()` to set the `preloadAfterLoad` option rather than the JS-based function you had. This is cleaner, but maybe you have reasons why the JS solution is preferrable to `wp_is_mobile()`?

I have set up phpunit with a basic test for the new way of injecting the config, and ensuring the "smart" `preloadAfterLoad` option works. I changed a few things to make testing easier down the line, such as converted the LazySizes class to a singleton so the instance can be retrieved if needed. I also had to move the call to `$this->_get_options()` to happen within the `wp_enqueue_scripts` action as the options were not available when I called `wp_localize_script()`, strangely. This also enabled me to change options from the tests, whereas I couldn't before.

I'm also going to send you a pull request without the tests incase you don't want any of that stuff cluttering up your repo, but I think the testing stuff will be useful. If you accept this pull request I'd like to continue refactoring the rest of the class.

Cheers
Joel.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

> One thing I'm not sure you'll like is that I am using the server-side wp_is_mobile() to set the preloadAfterLoad option rather than the JS-based function you had. This is cleaner, but maybe you have reasons why the JS solution is preferrable to wp_is_mobile()?

On a cached site PHP will not run thus is unable to detect user agent.

**Comment by joeldbirch** [comment]
Ah yes! Thanks. 

I'll have a think about some other ways to handle it. Hmm…

**Comment by joeldbirch** [comment]
I think the cleanest way to handle this is to concatenate the JS mobile detection script with the main 'lazysizes' external JS file. If it is prepended it will run before the main script so we can check for the 'smart' option and convert it to true or false before it is used.

It would add a build step, but it would avoid direct script printing while keeping http requests the same.

**Comment by joeldbirch** [comment]
I'm not sure `preloadAfterLoad` is working properly right now, so I'll close this pull request until I've tested more thoroughly.

**Pull request closed without merging**
